# Paths to dataset - replace paths with YOUR paths
classroomBase_path = "/viscam/projects/audio_nerf/datasets/release/Classroom/classroomBase"

dampenedBase_path = "/viscam/projects/audio_nerf/datasets/release/Dampened/dampenedBase"
dampenedRotation_path = "/viscam/projects/audio_nerf/datasets/release/Dampened/dampenedRotation"
dampenedTranslation_path = "/viscam/projects/audio_nerf/datasets/release/Dampened/dampenedTranslation"
dampenedPanel_path = "/viscam/projects/audio_nerf/datasets/release/Dampened/dampenedPanel"

hallwayBase_path = "/viscam/projects/audio_nerf/datasets/release/Hallway/hallwayBase"
hallwayRotation_path = "/viscam/projects/audio_nerf/datasets/release/Hallway/hallwayRotation"
hallwayTranslation_path = "/viscam/projects/audio_nerf/datasets/release/Hallway/hallwayTranslation"
hallwayPanel1_path = "/viscam/projects/audio_nerf/datasets/release/Hallway/hallwayPanel1"
hallwayPanel2_path = "/viscam/projects/audio_nerf/datasets/release/Hallway/hallwayPanel2"
hallwayPanel3_path = "/viscam/projects/audio_nerf/datasets/release/Hallway/hallwayPanel3"

complexBase_path = "/viscam/projects/audio_nerf/datasets/release/Complex/complexBase"
complexRotation_path = "/viscam/projects/audio_nerf/datasets/release/Complex/complexRotation"
complexTranslation_path = "/viscam/projects/audio_nerf/datasets/release/Complex/complexTranslation"

# Path to music files used for demos
music_files_for_trajectory_path = "/viscam/projects/audio_nerf/code_release/example_trajectories/source_audios"


# Path to HRIRs
HRIR_dataset_dir = "/viscam/projects/audio_nerf/code_release/HRIRs"

shoebox_L01_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/28"
shoebox_L06_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L06_planar"
shoebox_L11_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L11_planar"
shoebox_L16_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L16_planar"
shoebox_L21_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L21_planar"
shoebox_L26_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L26_planar"
shoebox_L31_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L31_planar"
shoebox_L36_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L36_planar"
shoebox_L41_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L41_planar"
shoebox_L46_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L46_planar"
shoebox_L51_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L51_planar"
shoebox_L56_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L56_planar"

shoebox00_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/00"
shoebox01_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/01"
shoebox02_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/02"
shoebox03_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/03"
shoebox04_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/04"
shoebox05_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/05"
shoebox06_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/06"
shoebox07_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/07"
shoebox08_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/08"
shoebox09_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/09"
shoebox10_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/10"
shoebox11_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/11"
shoebox12_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/12"
shoebox13_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/13"
shoebox14_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/14"
shoebox15_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/15"
shoebox16_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/16"
shoebox17_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/17"
shoebox18_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/18"
shoebox19_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/19"
shoebox20_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/20"
shoebox21_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/21"
shoebox22_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/22"
shoebox23_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/23"
shoebox24_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/24"
shoebox25_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/25"
shoebox26_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/26"
shoebox27_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/27"
shoebox28_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/28"
shoebox29_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/29"
shoebox30_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/30"
shoebox31_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/31"
shoebox32_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/32"
shoebox33_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/33"
shoebox34_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/34"
shoebox_offset_far_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/far"

shoebox_L1_0_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/L1_0"
shoebox_L1_1dBFS_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/L1_1dBFS"
shoebox_L1_2dBFS_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/L1_2dBFS"
shoebox_L1_neg1dBFS_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/L1_neg1dBFS"
shoebox_L1_neg3dBFS_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/L1_neg3dBFS"
shoebox_L1_neg5dBFS_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/L1_neg5dBFS"
shoebox_L1_neg7dBFS_path = "/workspace/haa_main_multi/Mods_by_Luka/Zhao_database/shoebox_L1_planar/L1_neg7dBFS"

